from selenium.webdriver.common.by import By
from src.testproject.classes import DriverStepSettings, StepSettings
from src.testproject.decorator import report_assertion_errors
from src.testproject.enums import SleepTimingType
from src.testproject.sdk.drivers import webdriver
import pytest


"""
This pytest test was automatically generated by TestProject
    Project: My first Project
    Package: TestProject.temperatura.inicioSesionCSV
    Test: Inicio Sesión CSV
    Generated by: JOSE ANDREI PINTO AVILA (japinto08@ucatolica.edu.co)
    Generated on 10/04/2021, 23:24:29
"""


@pytest.fixture()
def driver():
    driver = webdriver.Chrome(token="Lt9WBjdUZ31hSK6CDXfKlxOXlr7M_O5qW4VrqOMOvFc",
                              project_name="My first Project",
                              job_name="Inicio Sesión CSV")
    step_settings = StepSettings(timeout=15000,
                                 sleep_time=500,
                                 sleep_timing_type=SleepTimingType.Before)
    with DriverStepSettings(driver, step_settings):
        yield driver
    driver.quit()


@report_assertion_errors
def test_main(driver):
    """Inicio de sesión con set de pruebas."""
    # Test Parameters
    # Auto generated application URL parameter
    ApplicationURL = "http://localhost:3000/"
    email = "japinto08@ucatolica.edu.co"  # Valores de Email
    psw = "123456"  # valor de pasword

    # 1. Navigate to '{ApplicationURL}'
    # Navigates the specified URL (Auto-generated)
    driver.get(f'{ApplicationURL}')

    # 2. Click 'Iniciar Sesion'
    iniciar_sesion = driver.find_element(By.XPATH,
                                         "//a[. = 'Iniciar Sesion']")
    iniciar_sesion.click()

    # 3. Click 'email'
    email = driver.find_element(By.CSS_SELECTOR,
                                "#email")
    email.click()

    # 4. Type '{email}' in 'email'
    email = driver.find_element(By.CSS_SELECTOR,
                                "#email")
    email.send_keys(f'{email}')

    # 5. Click 'password'
    password = driver.find_element(By.CSS_SELECTOR,
                                   "#password")
    password.click()

    # 6. Type '{psw}' in 'password'
    password = driver.find_element(By.CSS_SELECTOR,
                                   "#password")
    password.send_keys(f'{psw}')

    # 7. Click 'Iniciar'
    iniciar = driver.find_element(By.XPATH,
                                  "//button[. = 'Iniciar']")
    iniciar.click()

    # 8. Click 'Estadistica'
    estadistica = driver.find_element(By.XPATH,
                                      "//a[. = 'Estadistica']")
    estadistica.click()
