from selenium.webdriver.common.by import By
from src.testproject.classes import DriverStepSettings, StepSettings
from src.testproject.decorator import report_assertion_errors
from src.testproject.enums import SleepTimingType
from src.testproject.sdk.drivers import webdriver
import pytest


"""
This pytest test was automatically generated by TestProject
    Project: My first Project
    Package: TestProject.temperatura.regUsuarios
    Test: Registro de Usuarios
    Generated by: JOSE ANDREI PINTO AVILA (japinto08@ucatolica.edu.co)
    Generated on 10/04/2021, 23:27:55
"""


@pytest.fixture()
def driver():
    driver = webdriver.Chrome(token="Lt9WBjdUZ31hSK6CDXfKlxOXlr7M_O5qW4VrqOMOvFc",
                              project_name="My first Project",
                              job_name="Registro de Usuarios")
    step_settings = StepSettings(timeout=15000,
                                 sleep_time=500,
                                 sleep_timing_type=SleepTimingType.Before)
    with DriverStepSettings(driver, step_settings):
        yield driver
    driver.quit()


@report_assertion_errors
def test_main(driver):
    """\"1.Ingresar a la URL http:localhost/register.

    2.En la pantalla del sistema debe ir a la opción “Registrar”3.El sistema despliega el formulario de registro de usuario4.Se deben digitar los datos de forma correcta.5.Presiona el botón “Registrar”.La aplicación deja al usuario en la pagina principal y habilita las opciones de los usuarios registrados y logeados..
    """
    # Test Parameters
    # Auto generated application URL parameter
    ApplicationURL = "http://localhost:3000/"

    # 1. Navigate to '{ApplicationURL}'
    # Navigates the specified URL (Auto-generated)
    driver.get(f'{ApplicationURL}')

    # 2. Click 'Registrar'
    registrar = driver.find_element(By.XPATH,
                                    "//a[. = 'Registrar']")
    registrar.click()

    # 3. Click 'firstname'
    firstname = driver.find_element(By.CSS_SELECTOR,
                                    "#firstname")
    firstname.click()

    # 4. Type 'Jose Andrei' in 'firstname'
    firstname = driver.find_element(By.CSS_SELECTOR,
                                    "#firstname")
    firstname.send_keys("Jose Andrei")

    # 5. Click 'lastname'
    lastname = driver.find_element(By.CSS_SELECTOR,
                                   "#lastname")
    lastname.click()

    # 6. Type 'Pinto Avila' in 'lastname'
    lastname = driver.find_element(By.CSS_SELECTOR,
                                   "#lastname")
    lastname.send_keys("Pinto Avila")

    # 7. Click 'email'
    email = driver.find_element(By.CSS_SELECTOR,
                                "#email")
    email.click()

    # 8. Type 'japinto08@ucatolica.edu.co' in 'email'
    email = driver.find_element(By.CSS_SELECTOR,
                                "#email")
    email.send_keys("japinto08@ucatolica.edu.co")

    # 9. Click 'password'
    password = driver.find_element(By.CSS_SELECTOR,
                                   "#password")
    password.click()

    # 10. Type '123456' in 'password'
    password = driver.find_element(By.CSS_SELECTOR,
                                   "#password")
    password.send_keys("123456")

    # 11. Click 'Registrar1'
    registrar1 = driver.find_element(By.XPATH,
                                     "//button[. = 'Registrar']")
    registrar1.click()
