from selenium.webdriver.common.by import By
from selenium.webdriver.support.select import Select
from src.testproject.classes import DriverStepSettings, StepSettings
from src.testproject.decorator import report_assertion_errors
from src.testproject.enums import SleepTimingType
from src.testproject.sdk.drivers import webdriver
import pytest


"""
This pytest test was automatically generated by TestProject
    Project: My first Project
    Package: TestProject.temperatura.consultatemhum
    Test: Consulta temperatura y humedad
    Generated by: JOSE ANDREI PINTO AVILA (japinto08@ucatolica.edu.co)
    Generated on 10/04/2021, 23:26:11
"""


@pytest.fixture()
def driver():
    driver = webdriver.Chrome(token="Lt9WBjdUZ31hSK6CDXfKlxOXlr7M_O5qW4VrqOMOvFc",
                              project_name="My first Project",
                              job_name="Consulta temperatura y humedad")
    step_settings = StepSettings(timeout=15000,
                                 sleep_time=500,
                                 sleep_timing_type=SleepTimingType.Before)
    with DriverStepSettings(driver, step_settings):
        yield driver
    driver.quit()


@report_assertion_errors
def test_main(driver):
    """Consulta de datos de clima de la ciudad seleccionada."""
    # Test Parameters
    # Auto generated application URL parameter
    ApplicationURL = "http://localhost:3000/"

    # 1. Navigate to '{ApplicationURL}'
    # Navigates the specified URL (Auto-generated)
    driver.get(f'{ApplicationURL}')

    # 2. Click 'ciudades'
    ciudades = driver.find_element(By.CSS_SELECTOR,
                                   "#FormControlCiudad")
    ciudades.click()

    # 3. Select the '1' option in 'ciudades'
    ciudades = driver.find_element(By.CSS_SELECTOR,
                                   "#FormControlCiudad")
    Select(ciudades).select_by_value("1")

    # 4. Click 'ciudades'
    ciudades = driver.find_element(By.CSS_SELECTOR,
                                   "#FormControlCiudad")
    ciudades.click()

    # 5. Click 'Adicionar Ciudad'
    adicionar_ciudad = driver.find_element(By.CSS_SELECTOR,
                                           "#adicionarCiudad")
    adicionar_ciudad.click()

    # 6. Scroll window by ('0','400')
    driver.execute_script("window.scrollBy(0,400)")

    # 7. Click 'Ver Informacion'
    ver_informacion = driver.find_element(By.CSS_SELECTOR,
                                          "#seleCiudad")
    ver_informacion.click()
