from selenium.webdriver.common.by import By
from selenium.webdriver.support.select import Select
from src.testproject.classes import DriverStepSettings, StepSettings
from src.testproject.decorator import report_assertion_errors
from src.testproject.enums import SleepTimingType
from src.testproject.sdk.drivers import webdriver
import pytest


"""
This pytest test was automatically generated by TestProject
    Project: My first Project
    Package: TestProject.temperatura.RegManualDatos
    Test: Registro Manual de datos
    Generated by: JOSE ANDREI PINTO AVILA (japinto08@ucatolica.edu.co)
    Generated on 10/04/2021, 23:25:19
"""


@pytest.fixture()
def driver():
    driver = webdriver.Chrome(token="Lt9WBjdUZ31hSK6CDXfKlxOXlr7M_O5qW4VrqOMOvFc",
                              project_name="My first Project",
                              job_name="Registro Manual de datos")
    step_settings = StepSettings(timeout=15000,
                                 sleep_time=500,
                                 sleep_timing_type=SleepTimingType.Before)
    with DriverStepSettings(driver, step_settings):
        yield driver
    driver.quit()


@report_assertion_errors
def test_main(driver):
    """Registro manual de datos."""
    # Test Parameters
    # Auto generated application URL parameter
    ApplicationURL = "http://localhost:3000/"

    # 1. Navigate to '{ApplicationURL}'
    # Navigates the specified URL (Auto-generated)
    driver.get(f'{ApplicationURL}')

    # 2. Click 'Iniciar Sesion'
    iniciar_sesion = driver.find_element(By.XPATH,
                                         "//a[. = 'Iniciar Sesion']")
    iniciar_sesion.click()

    # 3. Click 'email'
    email = driver.find_element(By.CSS_SELECTOR,
                                "#email")
    email.click()

    # 4. Type 'japinto08@ucatolica.edu.co' in 'email'
    email = driver.find_element(By.CSS_SELECTOR,
                                "#email")
    email.send_keys("japinto08@ucatolica.edu.co")

    # 5. Click 'password'
    password = driver.find_element(By.CSS_SELECTOR,
                                   "#password")
    password.click()

    # 6. Type '123456' in 'password'
    password = driver.find_element(By.CSS_SELECTOR,
                                   "#password")
    password.send_keys("123456")

    # 7. Click 'Iniciar'
    iniciar = driver.find_element(By.XPATH,
                                  "//button[. = 'Iniciar']")
    iniciar.click()

    # 8. Click 'Formulario'
    formulario = driver.find_element(By.XPATH,
                                     "//a[. = 'Formulario']")
    formulario.click()

    # 9. Click 'Nuevo Registro'
    nuevo_registro = driver.find_element(By.XPATH,
                                         "//button[. = 'Nuevo Registro']")
    nuevo_registro.click()

    # 10. Click 'temperatura'
    temperatura = driver.find_element(By.CSS_SELECTOR,
                                      "#inputTemperatura")
    temperatura.click()

    # 11. Type '22' in 'temperatura'
    temperatura = driver.find_element(By.CSS_SELECTOR,
                                      "#inputTemperatura")
    temperatura.send_keys("22")

    # 12. Click 'humedad'
    humedad = driver.find_element(By.CSS_SELECTOR,
                                  "#inputHumedad")
    humedad.click()

    # 13. Type '33' in 'humedad'
    humedad = driver.find_element(By.CSS_SELECTOR,
                                  "#inputHumedad")
    humedad.send_keys("33")

    # 14. Click 'FormControlPais'
    formcontrolpais = driver.find_element(By.CSS_SELECTOR,
                                          "#FormControlPais")
    formcontrolpais.click()

    # 15. Select the '1' option in 'FormControlPais'
    formcontrolpais = driver.find_element(By.CSS_SELECTOR,
                                          "#FormControlPais")
    Select(formcontrolpais).select_by_value("1")

    # 16. Click 'FormControlPais'
    formcontrolpais = driver.find_element(By.CSS_SELECTOR,
                                          "#FormControlPais")
    formcontrolpais.click()

    # 17. Click 'id_ciudad'
    id_ciudad = driver.find_element(By.CSS_SELECTOR,
                                    "#FormControlCiudad")
    id_ciudad.click()

    # 18. Select the '1' option in 'id_ciudad'
    id_ciudad = driver.find_element(By.CSS_SELECTOR,
                                    "#FormControlCiudad")
    Select(id_ciudad).select_by_value("1")

    # 19. Click 'id_ciudad'
    id_ciudad = driver.find_element(By.CSS_SELECTOR,
                                    "#FormControlCiudad")
    id_ciudad.click()

    # 20. Click 'fecha'
    fecha = driver.find_element(By.CSS_SELECTOR,
                                "#inputFecha")
    fecha.click()

    # 21. Type '2021-09-27T21:16' in 'fecha'
    fecha = driver.find_element(By.CSS_SELECTOR,
                                "#inputFecha")
    fecha.send_keys("2021-09-27T21:16")

    # 22. Click 'DIV2'
    div2 = driver.find_element(By.XPATH,
                               "//body/div/div/div")
    div2.click()

    # 23. Click 'Guardar'
    guardar = driver.find_element(By.XPATH,
                                  "//button[. = 'Guardar']")
    guardar.click()
